### ISSUE TITLE
Not see the Login Component on VueJs

### ISSUE THREAD

**Issue by fmicalizzi** [LaravelDaily/tutorials-api-auth#8]
Hello, I try to test the oauth access, but de client-vue only have the versions without protection.
The Api work fine, but I want know how you make the connections to the Api from vuejs.

Thanks if you can upload the others client-vue

**Comment by ModestasV** [comment]
@fmicalizzi Hello, I don't quite understand what is the problem exactly. Every single client-vue is updated to work with the API in the same branch, as an example:

https://github.com/LaravelDaily/tutorials-api-auth/pull/3/files#diff-f66fd052ff015ae72188aeb64f953f4f 

https://github.com/LaravelDaily/tutorials-api-auth/pull/2/files#diff-f66fd052ff015ae72188aeb64f953f4f

https://github.com/LaravelDaily/tutorials-api-auth/pull/1/files#diff-f66fd052ff015ae72188aeb64f953f4f

The logic overall is in this file: `client-vue/src/store/auth.js` which makes the calls to the API itself

**Comment by fmicalizzi** [comment]
@ModestasV

Thank you very much for your answer.

I think the problem is that in my deployment the client-vue are not updated as you show them to me in each of the Pulls

It might be doing something wrong in my installation.
But what happens to me generating different folders for the client side, is that the basic one is always displayed without auth, in fact the api, I can access it directly through the browser.

It is as if the middlewares are not applied

Maybe it can be me and my lack of knowledge, I am learning how APIs work with Laravel and I want to make one work safely from vue. Especially Passport

**Comment by ModestasV** [comment]
@fmicalizzi Oh, I see. You are cloning the repository and using Master which doesn't have the API. 

Please check https://help.github.com/en/github/getting-started-with-github/github-glossary#checkout - as you need to switch your local branch to the one you want to use. Or if you use a GUI client - check there for branches and pull the one you are interested in :)

**Comment by fmicalizzi** [comment]
Great @ModestasV 
I get it.

I'm going to move to the branch I need and download those files to do the tests.
Thank you very much again.

**Comment by ModestasV** [comment]
@fmicalizzi Awesome, hopefully, your tests will provide good results :)
